target:
  url: "https://www.example.com"
  path: "wp-json/wp/v2/posts"
  categories: "0" # Currently does not support optional url parameters
  per_page: "your_number_here" # Max is 100
keywords: ["list of strings to save into files"]
